version: '3'

services:

  mysql8:
    image: mysql:8.0.28
    platform: linux/x86_64
    container_name: practice_mysql
    restart: always
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test12345678
      MYSQL_DATABASE: testdatabase
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
